### ISSUE TITLE
package.json points to TypeScript git master rather than 1.5.0-beta? 

### ISSUE THREAD

**Issue by timfish** [pyarmak/aurelia-electron-starter#1]
Many thanks for this example.

Is there any reason not to use a pre-built TypeScript package? Its only a minor point but it downloaded the whole git repo (around 1.2GB) into my npm-cache on my laptop which took forever!

**Comment by pyarmak** [comment]
I think I did that because I was developing something earlier and wanted to be on the bleeding edge. 
I will update this repo as soon as I get my development environment set back up on my computer (I had my system ssd fail on me).

**Comment by pyarmak** [comment]
Solved in pull request #2.
