### ISSUE TITLE
err  Registry bower not found.

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [pyarmak/aurelia-electron-starter#3]
Hi, I cannot install packages. I got the following error.

Regards,

$ npm install
$ sudo npm install -g gulp
$ sudo npm install -g jspm
$ jspm install -y

err  Registry bower not found.
err  Unable to load registry bower
warn Installation changes not saved.

**Comment by HIRANO-Satoshi** [comment]
This does not fix the issue.

$ npm install bower

**Comment by HIRANO-Satoshi** [comment]
I fixed it.

I removed some lines related to bower from config.js. That worked.

I will send pull request later.

**Comment by timfish** [comment]
I think my pull request fixes the same issue via another means.

**Comment by pyarmak** [comment]
Solved by pull request #2. 
Thank you both.
